runtime: nodejs16

handlers:
  - url: /
    static_files: dist/apps/food-for-you/index.html
    upload: dist/apps/food-for-you/index.html

  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301
